CREATE TABLE application_users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    email VARCHAR(254) NOT NULL,
    password_hash VARCHAR(100) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_application_users PRIMARY KEY (id),
    CONSTRAINT ck_application_users_email_not_blank CHECK (btrim(email) <> ''),
    CONSTRAINT ck_application_users_password_hash_not_blank CHECK (btrim(password_hash) <> '')
);

CREATE UNIQUE INDEX uq_application_users_lower_email ON application_users (lower(email));
